apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
    group: system
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 32500    
    protocol: TCP
  selector:
    app: docker-registry
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
        tier: backend
    spec:
      containers:
      - name: docker-registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: registry
        # Volumes im Container
        volumeMounts:
        - mountPath: "/var/lib/registry"
          subPath: registry        
          name: "registry-data"
      # Volumes in Host
      volumes:
      - name: "registry-data"
        hostPath:
        persistentVolumeClaim:
         claimName: data-claim             