apiVersion: v1
kind: Service
metadata:
  name: registry-frontend
  labels:
    app: registry-frontend
    group: system
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32580    
    protocol: TCP
  selector:
    app: registry-frontend
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: registry-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-frontend
  template:
    metadata:
      labels:
        app: registry-frontend
        tier: frontend
    spec:
      containers:
      - name: registry-frontend
        image: konradkleine/docker-registry-frontend:v2
        env:
        - name: ENV_DOCKER_REGISTRY_HOST
          value: docker-registry
        - name: ENV_DOCKER_REGISTRY_PORT
          value: "5000" 
        ports:
        - containerPort: 80
          name: frontend
          
         