apiVersion: v1
kind: Service
metadata:
  name: kanboard
  labels:
    app: kanboard
    group: devops    
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32200  
    protocol: TCP
  selector:
    app: kanboard
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanboard
  template:
    metadata:
      labels:
        app: kanboard
        group: devops
        tier: frontend
    spec:
      containers:
      - name: kanboard
        image: kanboard/kanboard
        ports:
        - containerPort: 80
          name: kanboard
        # Volumes im Container
        volumeMounts:
        - mountPath: "/var/www/app/data"
          subPath: kanboard/data 
          name: "kanboard-data"
      # Volumes in Host - Verzeichnis kanboard/data mit Zugriff 777 anlegen
      volumes:
      - name: "kanboard-data"
        persistentVolumeClaim:
         claimName: data-claim 
   